# Generated by Django 4.2 on 2023-05-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0002_reserve_time_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='decoration',
            field=models.BooleanField(default=False, verbose_name='Decoración'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='num_person',
            field=models.IntegerField(verbose_name='Número de personas'),
        ),
    ]
